// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VuThiThanh103.Data;

namespace VuThiThanh103.Migrations
{
    [DbContext(typeof(VuThiThanh103Context))]
    partial class VuThiThanh103ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VuThiThanh103.Models.PersonVTT103", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonId");

                    b.ToTable("PersonVTT103");
                });
#pragma warning restore 612, 618
        }
    }
}
